package jlee.app.cal.wampfirebasemessaging;

import android.util.Log;

import com.google.firebase.iid.FirebaseInstanceId;
import com.google.firebase.iid.FirebaseInstanceIdService;

//This class gets the device token and uses the SharedPrefManager class we created to save the token. Since it is a service,
//it runs in the background without the user knowing.
public class MyFirebaseInstanceIDService extends FirebaseInstanceIdService
{
    private static final String TAG = "MyFirebaseIIDService";

    public void onTokenRefresh()
    {
        //Getting registration token. Every device generates a unique token to receive notifications
        String refreshedToken = FirebaseInstanceId.getInstance().getToken();
        //Displaying token on logcat
        Log.d("myfirebaseid", "Refreshed token: " + refreshedToken);
        //calling the method store token and passing token
        storeToken(refreshedToken);
    }
    private void storeToken(String token)
    {
        //SharedPrefManager is a class we created to save the token generated by Firebase for the device. Every device has a unique token to receive notifications
        SharedPrefManager.getInstance(getApplicationContext()).saveDeviceToken(token);
    }
}